### PR TITLE
Check reaper in main binary

### LINKED ISSUE #774: Move check-reaper into main Kuberhealthy binary
We should move the check-reaper cronjob directly into Kuberhealthy and run it on a ticker.  This will make the check reaper more reliable, and decreases our chance of a cronjob failing to schedule/run, which results in a pile of completed/running/failed check pods building up.

### PR DESCRIPTION
**Pull request by integrii**
The branch has a typo - sorry.

This removes the existing check reaper in favor of a check reaper that is integrated directly into the main Kuberhealthy binary.  Additionally, a bunch of context plumbing has been done so that all external check routines and now directly linked to the parent context created at program start.

The check reaper will start when checks start and stop when checks shutdown (which is normally based on master status).

Fixes #774 👍

### CODE REVIEW

**Comment by integrii** [comment]
This is testable with the `kuberhealthy/kuberhealthy:reaper` image right now.

**Comment by joshulyne** [comment]
lgtm! 👍

File: cmd/kuberhealthy/config.go [hunk 1]
```diff
@@ -13,15 +13,17 @@ import (
...
+	EnableForceMaster         bool          `yaml:"enableForceMaster,omitempty"`
+	LogLevel                  string        `yaml:"logLevel,omitempty"`
+	InfluxUsername            string        `yaml:"influxUsername,omitempty"`
+	InfluxPassword            string        `yaml:"influxPassword,omitempty"`
+	InfluxURL                 string        `yaml:"influxURL,omitempty"`
+	InfluxDB                  string        `yaml:"influxDB,omitempty"`
+	EnableInflux              bool          `yaml:"enableInflux,omitempty"`
+	ExternalCheckReportingURL string        `yaml:"externalCheckReportingURL,omitempty"`
+	CheckCleanupDuration      time.Duration `yaml:"checkCleanupDuration,omitempty"`
+	MaxCheckPods              int           `yaml:"maxCheckPods,omitempty"`
```
Comment (joshulyne) [inline cmd/kuberhealthy/config.go:26]: can we set a default `MaxCheckPods` ? or if we want the default behavior to be 0 then checker pods dont stay around... 🤷

File: deploy/helm/kuberhealthy/values.yaml [hunk 2]
```diff
@@ -2,6 +2,10 @@
 # This is a YAML-formatted file.
 # Declare variables to be passed into your templates.
 
+checkReaper:
+  checkCleanupDuration: 15m # the maximum age of check pods before being reaped
```
Comment (joshulyne) [inline deploy/helm/kuberhealthy/values.yaml:6]: can we rename this? not accurate description since this only applies to khjobs not checks... 
```suggestion
  jobCleanupDuration: 15m # the maximum age of kh job pods before being reaped
```

File: deploy/helm/kuberhealthy/templates/configmap.yaml [hunk 3]
```diff
@@ -12,4 +12,6 @@ data:
     influxPassword: "" # Password for the InfluxDB instance
     influxURL: "" # Address for the InfluxDB instance
     influxDB: "http://localhost:8086" # Name of the InfluxDB database
-    enableInflux: false # Set to true to enable metric forwarding to Infux DB
\ No newline at end of file
+    enableInflux: false # Set to true to enable metric forwarding to Infux DB
+    checkCleanupDuration: {{ .Values.checkReaper.checkCleanupDuration }}
```
Comment (joshulyne) [inline deploy/helm/kuberhealthy/templates/configmap.yaml:16]:
```suggestion
    jobCleanupDuration: {{ .Values.checkReaper.jobCleanupDuration }}
```

File: cmd/kuberhealthy/reaper.go [hunk 4]
```diff
@@ -267,21 +249,21 @@ func khJobDelete(client *khjobcrd.KHJobV1Client) error {
...
 	}
 
-	log.Infoln("Found", len(list.Items), "khjobs")
+	log.Infoln("checkReaper: Found", len(list.Items), "khjobs")
 
 	// Range over list and delete khjobs
 	for _, j := range list.Items {
-		if jobConditions(j, JobDeleteTimeDuration, "Completed") {
-			log.Infoln("Deleting khjob", j.Name)
+		if jobConditions(j, cfg.CheckCleanupDuration, "Completed") {
```
Comment (joshulyne) [inline cmd/kuberhealthy/reaper.go:262]:
```suggestion
		if jobConditions(j, cfg.jobCleanupDuration, "Completed") {
```

File: cmd/kuberhealthy/config.go [hunk 5]
```diff
@@ -13,15 +13,17 @@ import (
...
+	ListenAddress             string        `yaml:"listenAddress,omitempty"`
+	EnableForceMaster         bool          `yaml:"enableForceMaster,omitempty"`
+	LogLevel                  string        `yaml:"logLevel,omitempty"`
+	InfluxUsername            string        `yaml:"influxUsername,omitempty"`
+	InfluxPassword            string        `yaml:"influxPassword,omitempty"`
+	InfluxURL                 string        `yaml:"influxURL,omitempty"`
+	InfluxDB                  string        `yaml:"influxDB,omitempty"`
+	EnableInflux              bool          `yaml:"enableInflux,omitempty"`
+	ExternalCheckReportingURL string        `yaml:"externalCheckReportingURL,omitempty"`
+	CheckCleanupDuration      time.Duration `yaml:"checkCleanupDuration,omitempty"`
```
Comment (joshulyne) [inline cmd/kuberhealthy/config.go:25]: rename to `JobCleanupDuration` since this only applies to khjobs cleanup not khchecks
```suggestion
	JobCleanupDuration      time.Duration `yaml:"jobCleanupDuration,omitempty"`
```

**Review by joshulyne — COMMENTED** [review]
few comments but works as expected!

**Review by joshulyne — APPROVED** [review]
lgtm
